{% set name = "pyls-mypy" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fd83028961f0ca9eb3048b7a01cf42a9e3d46d8ea4935c1424c33da22c3eb03

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python-language-server
    - mypy
    - flake8
    - configparser

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyls_mypy

about:
  home: https://github.com/tomv564/pyls-mypy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Mypy plugin for the Python Language Server'
  description: |
    Mypy plugin for the Python Language Server
  dev_url: https://github.com/tomv564/pyls-mypy

extra:
  recipe-maintainers:
    - ccordoba12
    - steff456
    - andfoy
